import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { AspectRatio, Box, Container, Image, Spoiler, Title } from '@mantine/core';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <AspectRatio ratio={900 / 1600} sx={{ maxWidth: 300 }} mx="auto">
        Main App from App.ysx
        <div style={{ width: 240, marginLeft: 'auto', marginRight: 'auto' }}>
        <Image
        width={900}
        height={1600}
        fit="contain"
        src="https://images.unsplash.com/photo-1527118732049-c88155f2107c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=720&q=80"
        alt="Panda"
      />
      
      </div>
      </AspectRatio>
      <Box
  sx={(theme) => ({
    backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[6] : theme.colors.gray[0],
    textAlign: 'center',
    padding: theme.spacing.xl,
    borderRadius: theme.radius.md,
    
    cursor: 'pointer',

    '&:hover': {
      backgroundColor:
        theme.colorScheme === 'dark' ? theme.colors.dark[5] : theme.colors.gray[1],
    },
  })}
>
<Title order={1}> Welcome to Amigos pet clinic</Title>
        <p>
        We are providing great service at low cost in greater Pasadena, Houston for few years
        </p>
</Box>
      {/* <Spoiler maxHeight={120} showLabel="Show more" hideLabel="Hide">
      {/* Content here */} 
    {/* </Spoiler> */}
      

      {/* <Container size="xs">
    xs container with xs horizontal padding
  </Container>  */}

      </main>
    </>
  )
}
